# Generated by Django 6.0 on 2026-01-16 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Ecosysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('localisation', models.CharField(help_text='Localisation typique ou climat', max_length=200, verbose_name='Localisation')),
            ],
            options={
                'verbose_name': 'Écosystème',
                'verbose_name_plural': 'Écosystèmes',
            },
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commun', models.CharField(max_length=100, verbose_name='Nom Commun')),
                ('nom_scientifique', models.CharField(max_length=150, unique=True, verbose_name='Nom Scientifique')),
                ('esperance_vie', models.IntegerField(help_text='Espérance de vie moyenne en années', verbose_name='Espérance de Vie')),
                ('poids', models.FloatField(help_text='Poids moyen en kg', verbose_name='Poids (kg)')),
                ('taille', models.FloatField(help_text='Taille moyenne/longueur en mètres', verbose_name='Taille (m)')),
                ('statut_conservation', models.CharField(choices=[('EX', 'Éteint (Extinct)'), ('EW', "Éteint à l'état sauvage (Extinct in the Wild)"), ('CR', 'En danger critique (Critically Endangered)'), ('EN', 'En danger (Endangered)'), ('VU', 'Vulnérable (Vulnerable)'), ('NT', 'Quasi menacé (Near Threatened)'), ('LC', 'Préoccupation mineure (Least Concern)'), ('DD', 'Données insuffisantes (Data Deficient)'), ('NE', 'Non évalué (Not Evaluated)')], max_length=2, verbose_name='Statut de Conservation')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_decouverte', models.DateField(blank=True, null=True, verbose_name='Date de Découverte')),
                ('image', models.ImageField(blank=True, null=True, upload_to='creatures/', verbose_name='Image')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatures', to='api.categorie', verbose_name='Catégorie')),
                ('ecosystemes', models.ManyToManyField(related_name='creatures', to='api.ecosysteme', verbose_name='Écosystèmes')),
            ],
            options={
                'verbose_name': 'Créature',
                'verbose_name_plural': 'Créatures',
            },
        ),
    ]
